import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="w-screen h-screen flex flex-col items-center justify-center bg-slate-300 text-red-400">
          <h1>Layout Principal</h1>
          <Link href={'/multimidia'} className= "w-48 h-10 flex flex items-center justify-center bg-purple text-purple">Página de multimidia</Link>
        {children}
        </main>
      </body>
    </html>
  );
}
